# Generated by Django 3.2.8 on 2023-05-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alquiler',
            unique_together={('codigo_alquiler', 'id_estudiante', 'id_bicicleta', 'fecha_alquiler')},
        ),
        migrations.AlterUniqueTogether(
            name='campuspromocion',
            unique_together={('id_campus', 'codigo_promocion', 'inicio_promocion')},
        ),
        migrations.AlterUniqueTogether(
            name='mantenimiento',
            unique_together={('codigo_mantenimiento', 'id_bicicleta', 'id_empleado')},
        ),
    ]
